### ISSUE TITLE
Make entering your 3 things easier

### ISSUE THREAD

**Issue by oreissig** [aviflax/3things#7]
I'd like to use tab to enter the next thing, but it will select the next thing's checkbox instead. I have to press tab twice, which is kind of tedious, because typically you'd enter all your things first before checking any of them.

The ideal order of focus would be: 1st text field, 2nd text field, 3rd text field, 1st checkbox, 2nd checkbox, 3rd checkbox, 1st text field, ...

**Comment by aviflax** [comment]
@oreissig this is now done. Thanks for the suggestion, and sorry for the delay.
